

# Check server url https://hello-truck-server.fly.dev/


POST http://localhost:3000/auth/customer/send-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929"
}

### Verify OTP
POST http://localhost:3000/auth/customer/verify-otp
Content-Type: application/json

{
  "phoneNumber": "6300045929",
  "otp": "123456"
}

### Get user profile
GET http://localhost:3000/customer/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

### Update user profile
PUT http://localhost:3000/customer/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

{
  "email": "john.doe@example.com"
}

### get gst details
GET http://localhost:3000/customer/gst
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

### Add GST details
POST http://localhost:3000/customer/gst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk0MjkyLCJleHAiOjE3NTMyOTUxOTJ9.TSD2Kb7CXsOxH4HzIzEkFVo-UEncVnEWNO900Ph3qc4

{
  "gstNumber": "27AAACF2234C1Z5",
  "businessName": "Hello Truck Pvt Ltd",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Update GST details
PUT http://localhost:3000/customer/gst/da41269f-9325-492b-9aad-045432a1003a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1MjcwLCJleHAiOjE3NTMyOTYxNzB9.rtGT_UtIZ_9yQfsJmNRV6l4v_PoUS-L9MyDFZ_kADys

{

  "gstNumber": "27AAACF2234C1Z5",
  "businessName": "Hello Truck Pvt Ltd Updated",
  "businessAddress": "123, Main Street, Mumbai, Maharashtra, 400001"
}

### Deactivate GST details
POST http://localhost:3000/customer/gst/deactivate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwidXNlcklkIjoiNzM0ZDJjMDQtM2ViZC00NTI4LTg1ZmQtNGYxYmRhZmJmMTczIiwiaGFzQ29tcGxldGVkT25ib2FyZGluZyI6dHJ1ZSwiaWF0IjoxNzUzMjk1NDg1LCJleHAiOjE3NTMyOTYzODV9.F5TC3lWHZS3sBdjPIyB5nNdhQJL1x3f-ZaEP9eMxuw8

{
  "id": "da41269f-9325-492b-9aad-045432a1003a"
}



