// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoKlxxs974kEFQGCDgctMXb4HBMHYE_c',
    appId: '1:893334775463:android:76c40739020afb69f89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    storageBucket: 'civicsense-473112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_yaaZ3LIZAcIkHDWS7Y4fmR_U5B8EZBs',
    appId: '1:893334775463:ios:c77575e608c43887f89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    storageBucket: 'civicsense-473112.firebasestorage.app',
    androidClientId: '893334775463-e5ufve4imaf126vlkblaphefollsq8p8.apps.googleusercontent.com',
    iosClientId: '893334775463-hfr4dl2qjd29ef5li5f3k54cc6l8jbc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloTruckApp',
  );

}